"""A seeded demo walk over synthetic terrain — ships a sealed receipt.

The receipt is regenerated by CI and must match the committed bytes
(the stale-receipt gate): the walk is fully determined by
(genome, terrain, ticks, probe_at), so any drift is a caught lie.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from moth_cells import (Genome, from_corpus_rows, replay, verify, walk)
from moth_cells.vendor_canonical import canonical_dumps


def build_terrain():
    rows = []
    specs = [
        ("parse.rs", "parse", 3, 2, False),
        ("parse.rs", "lex", 1, 1, False),
        ("render.rs", "draw", 2, 4, False),
        ("render.rs", "composite", 4, 1, False),
        ("net.rs", "handle", 2, 4, False),
        ("net.rs", "decoy_route", 4, 4, True),   # decoy: hot, sink-verified safe
    ]
    for f, name, entry_e, taint_e, decoy in specs:
        rows.append({
            "file_path": f, "language": "rust", "loc": 12,
            "surface": {
                "name": name,
                "entry_points": (65536 * entry_e) // 4,
                "taint_marks": (65536 * taint_e) // 4,
                **({"decoy": True, "sink_verified_safe": True} if decoy else {}),
            },
        })
    return from_corpus_rows(rows)


def main() -> int:
    cells = build_terrain()
    genome = Genome(seed=0xC0CA9E, move_weights=(49152, 16384, 0),
                    attention_bias=8192)
    hunter, rows = walk(genome, cells, 60, probe_at=5)
    assert replay(genome, cells, 60, probe_at=5), "replay not byte-identical"

    out = Path(__file__).parent / "demo.walk.jsonl"
    with out.open("w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(canonical_dumps(r).decode("utf-8") + "\n")
    ok, errors = verify([dict(r) for r in rows])
    print(f"walk sealed ({'intact' if ok else errors}) -> {out}")
    print(f"hunter: genome={genome.genome_id} moves={hunter.moves} "
          f"findings={hunter.findings} alive={hunter.alive} "
          f"dormant={hunter.dormant} energy={hunter.energy_q16}/65536")
    kinds = {}
    for r in rows:
        kinds[r["kind"]] = kinds.get(r["kind"], 0) + 1
    print(f"rows: {kinds}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
